# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled tmp453
patreon: # Replace with a single Patreon tmp453
open_collective: # Replace with a single Open Collective tmp453
ko_fi: # Replace with a single Ko-fi tmp453
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay tmp453
issuehunt: # Replace with a single IssueHunt tmp453
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar tmp453
buy_me_a_coffee: # Replace with a single Buy Me a Coffee tmp453
thanks_dev: # Replace with a single thanks.dev tmp453
